version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "MaterialTracker.Application/MaterialTracker.Application.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - save_cache:
          paths:
            - C:\Users\circleci\.nuget\packages
          key: dotnet-packages-v1-{{ checksum "MaterialTracker.Application/MaterialTracker.Application.csproj" }}
      - run:
          name: "Print Working Directory"
          command: pwd
      - run:
          name: "Test the executable"
          command: dotnet.exe test -v n --results-directory:test_coverage --collect:"Code Coverage"
      - store_artifacts:
          path: .\test_coverage
      - store_test_results:
          path: .\test-results

  build:
    executor:
      name: windows/default
      shell: powershell.exe
    steps:
      - checkout
      - run:
          name: "Run Build step"
          command: dotnet.exe publish -c Release -r win10-x64
      - store_artifacts:
          path: .\MaterialTracker.Application\bin\Release\netcoreapp3.1\win10-x64\publish\MaterialTracker.Application.exe

workflows:
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test